version: '3.3'

networks:
  internet: {}
  no-internet:
    internal: true

services:
  web400site:
    image: bitnami/php-fpm:7.4
    container_name: web400site
    networks:
      - no-internet
    volumes:
      - ./web/www/:/var/www/
      - ./web/configs/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./web/configs/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - ./web/configs/php.ini:/opt/bitnami/php/etc/php.ini
      - ./logs/web/:/var/log/php-fpm/
  web400:
    image: nginx:latest
    container_name: web400
    networks:
      - internet
      - no-internet
    ports:
      - 4043:4043/tcp
    volumes:
      - ./proxy/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/proxy/:/var/log/nginx/
      - ./web/www/:/var/www/
    links:
      - web400site
