version: "3.3"

networks:
  internet: {}
  no-internet:
    internal: true

services:
  web300site:
    image: php:7.2-apache
    container_name: web300site
    volumes:
      - ./web/src_flag:/var/www/flag
      - ./web/src:/var/www/html
      - ./web/configs/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./web/configs/ports.conf:/etc/apache2/ports.conf
      - ./web/configs/php.ini:/usr/local/etc/php/php.ini
      - ./logs/web-ssrf/:/var/log/apache2/
    networks:
      - no-internet

  web300:
    image: nginx:latest
    container_name: web300
    networks:
      - internet
      - no-internet
    ports:
      - 4042:4042/tcp
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/proxy/:/var/log/nginx/
    links:
      - web300site
